
##### Config file #####

configfile: "../default_protocol/pipelines/process_reads/config.yaml" #absolute path from annotation.js

##### Target rules #####

rule all:
    input:
        expand(config["output_path"]+ "/{file_stem}.csv", file_stem=config["file_stem"])

##### Modules #####
include: "rules/demultiplex.smk"
include: "rules/map.smk"

