
##### Configuration #####

barcodes = config["barcodes"].split(',')
barcode_string = ""
for i in barcodes:
    barcode_string+=" {}".format(i.lstrip("NB").lstrip("BC").lstrip("barcode"))


##### Target rules #####

rule all:
    input:
        expand(config["output_path"]+ "/{filename_stem}.csv", filename_stem=config["filename_stem"])

##### Modules #####
include: "rules/demultiplex.smk"
include: "rules/map.smk"

