{% set version = "1.2.1" %}

package:
  name: rampart
  version: {{ version }}

source:
  # url: https://github.com/artic-network/rampart/archive/v1.2.1.tar.gz
  folder: rampart
  # sha256: 3235c4296320bbfc06a80142d30ae9f36848bee7f563bc1677270883a77a9155
  path: ../..

requirements:
  build:
    - "nodejs>=10.4.1"
  run:
    - "nodejs>=10.4.1"

app:
  entry: rampart
  summary: "rampart"

build:
  number: 0
  noarch: generic

test:
  commands:
    - rampart --help

about:
  home: https://artic-network.github.io/rampart/
  license: AGPL-3.0-only
  summary: Read Assignment, Mapping, and Phylogenetic Analysis in Real Time
