

rule all:
    run:
        import time;
        for i in range(1, 6):
            print("####Running {}/5...".format(i), flush=True)
            time.sleep(1) # 1 second
        print("####Successfully completed", flush=True)