
##### Config file #####

configfile: "pipelines/rampart_demux_map/config.yaml"

##### Target rules #####

rule all:
    input:
        expand(config["outputPath"]+ "/annotated_reads/{file_stem}.fastq", file_stem=config["file_stem"])

##### Modules #####
include: "rules/demultiplex.smk"
include: "rules/map.smk"
include: "rules/bin.smk"

