##### Configuration #####

barcodes = config["barcodes"]
barcode_string = ""
for i in barcodes:
    barcode_string+=" {}".format(i)


##### Target rules #####

rule all:
    input:
        expand(config["outputPath"] + "/barcode_{barcode}.fastq",barcode=config["barcodes"])
        #this is saving the binned fastq in its own separate directory within a directory called binned. Can change this. 
        #output of this pipeline is both the fastq file and a csv report of the reads in that file, with respective annotations.

##### Modules #####

include: "rules/bin.smk"


